# fly.toml app configuration file generated for notes-mike on 2023-05-26T18:34:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notes-mike"
primary_region = "ams"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[[services]]
  protocol = ""
  internal_port = 3000
